# .github/workflows/deploy-firebase.yml
name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths:
      - "sites/**"
      - "shared/**"
      - "tools/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [univers, entertainment, podcast, glas-otoka, pitch-deck]

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Decide diff range
        id: range
        run: |
          BEFORE="${{ github.event.before }}"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            BEFORE=$(git rev-parse HEAD^)
          fi
          echo "before=$BEFORE" >> $GITHUB_OUTPUT

      - name: Check if site changed
        id: changes
        run: |
          if git diff --name-only ${{ steps.range.outputs.before }} ${{ github.sha }} | grep -qE "^sites/${{ matrix.site }}/|^shared/|^tools/|^package(-lock)?\.json$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with: { node-version: 20, cache: "npm" }

      - name: Install & Build
        if: steps.changes.outputs.changed == 'true'
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase
        if: steps.changes.outputs.changed == 'true'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          projectId: your-firebase-project-id
          target: ${{ matrix.site }}
          channelId: live
