name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          remote-user: deploy
          server-ip: ${{ secrets.SERVER_IP }}
          remote-path: /var/www/myapp
          local-path: ./dist
