name: Q Guard
on: [pull_request]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block core edits without approval
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref || 'main' }}...HEAD | tr '\n' ' ')
          echo "$CHANGED" | grep -E "\.amazonq/rules/core/" && { echo "❌ Core rules changed — manual approval required"; exit 1; } || echo "✓ Core intact"
      - name: Enforce narrative cap (optional)
        if: false
        run: echo "Cap enforced by agent; CI gate disabled by default."